# Generated by Django 4.2.8 on 2023-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('reps', models.IntegerField(verbose_name='reps')),
                ('series', models.IntegerField(verbose_name='series')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscle', models.CharField(max_length=200, verbose_name='muscle')),
            ],
        ),
        migrations.CreateModel(
            name='Sample_exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('reps', models.IntegerField(verbose_name='reps')),
                ('series', models.IntegerField(verbose_name='series')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscle', models.CharField(max_length=200, verbose_name='muscle')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_date', models.DateTimeField(verbose_name='workout date')),
            ],
        ),
    ]
